name: "CI: Run Tests, Lint/Format."

on:
  push:
    branches:
    - main
    
  pull_request:
    branches:
    - main

jobs:
  FileChecks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Mixed line endings
      uses: ymwymw/check-mixed-line-endings@v2
    - name: Large file check
      uses: ppremk/lfs-warning@v3.2
      with:
        filesizelimit: 10MB
    - name: Missing init modules
      run: |
        uv tool run pre-commit run --all-files detect-missing-init
    - name: Check .gitattributes rules
      run: |
        missing_attributes=$(git ls-files | git check-attr -a --stdin | grep 'text: auto' || printf '\n')
        if [ -n "$missing_attributes" ]; then
          printf '%s\n%s\n' '.gitattributes rule missing for the following files:' "$missing_attributes"
          exit 1
        else
          printf '%s\n' 'All files have a corresponding rule in .gitattributes'
        fi

  lintFormat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Set up Python
      run: uv python install
    - name: Install dependencies
      run: uv sync
    - name: Dead code Check
      run: uv run --no-project vulture src/ --min-confidence 80
    - name: Format code
      run: |
        uv run --no-project ruff format --check
        uv run --no-project ruff check
    - name: Validate pyproject.toml structure
      run: uv run --no-project pyproject-fmt --check pyproject.toml

  gitLeaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v2

  pytest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Set up Python
      run: uv python install
    - name: Install dependencies
      run: uv sync
    - name: Run unit tests
      run: uv run pytest --cov-report=xml --cov-report=term --durations 10
    - name: Coverage report comment
      if: github.event_name == 'pull_request'
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: coverage.xml

  typeCheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Set up Python
      run: uv python install
    - name: Install dependencies
      run: uv sync
    - name: Run ty
      run: uv run ty check